# Generated by Django 4.2.1 on 2023-06-12 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("housing", "0004_property_number_of_rooms"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="property",
            name="number_of_rooms",
        ),
        migrations.AddField(
            model_name="property",
            name="addres_link",
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="property",
            name="num_people",
            field=models.IntegerField(
                choices=[
                    (1, "1 people"),
                    (2, "2 people"),
                    (3, "3 people"),
                    (4, "4 people"),
                    (5, "5 people"),
                    (6, "6 people"),
                    (7, "7 people"),
                    (8, "8 people"),
                    (9, "9 people"),
                    (10, "10 people"),
                ],
                default=1,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="property",
            name="num_rooms",
            field=models.IntegerField(
                choices=[
                    (1, "1 room"),
                    (2, "2 room"),
                    (3, "3 room"),
                    (4, "4 room"),
                    (5, "5 room"),
                    (6, "6 room"),
                    (7, "7 room"),
                    (8, "8 room"),
                    (9, "9 room"),
                    (10, "10 room"),
                ],
                default=1,
            ),
            preserve_default=False,
        ),
    ]
