# Generated by Django 4.2.1 on 2023-06-12 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "housing",
            "0005_remove_property_number_of_rooms_property_addres_link_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="phone",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="property",
            name="addres_link",
            field=models.URLField(
                blank=True,
                help_text="Введите ссылку на адрес",
                null=True,
                verbose_name="Ссылка на адрес",
            ),
        ),
    ]
