# Generated by Django 4.2.1 on 2023-06-12 20:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("housing", "0006_property_phone_alter_property_addres_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="phone",
            field=models.CharField(
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Номер телефона должен быть в формате: '+999999999'. Максимальное количество символов: 15.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
            ),
        ),
    ]
