# Generated by Django 4.2.1 on 2023-06-12 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("housing", "0009_rename_num_people_property_num_guests_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="email",
            name="property",
        ),
        migrations.AddField(
            model_name="property",
            name="emails",
            field=models.ManyToManyField(to="housing.email"),
        ),
    ]
