# Generated by Django 4.2.1 on 2023-06-12 21:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("housing", "0010_remove_email_property_property_emails"),
    ]

    operations = [
        migrations.CreateModel(
            name="Phone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Номер телефона должен быть в формате: '+999999999'. Максимальное количество символов: 15.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="property",
            name="phone",
        ),
        migrations.AddField(
            model_name="property",
            name="phone",
            field=models.ManyToManyField(to="housing.phone"),
        ),
    ]
