# Generated by Django 4.2.1 on 2023-06-12 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("housing", "0011_phone_remove_property_phone_property_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="num_guests",
            field=models.IntegerField(
                choices=[
                    (1, "1 guest"),
                    (2, "2 guest"),
                    (3, "3 guest"),
                    (4, "4 guest"),
                    (5, "5 guest"),
                    (6, "6 guest"),
                    (7, "7 guest"),
                    (8, "8 guest"),
                    (9, "9 guest"),
                    (10, "10 guest"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="num_rooms",
            field=models.IntegerField(
                choices=[
                    (1, "1 room"),
                    (2, "2 rooms"),
                    (3, "3 rooms"),
                    (4, "4 rooms"),
                    (5, "5 rooms"),
                    (6, "6 rooms"),
                    (7, "7 rooms"),
                    (8, "8 rooms"),
                    (9, "9 rooms"),
                    (10, "10 rooms"),
                ]
            ),
        ),
    ]
